### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by apphead** [luc-github/FW-config-editor#6] opened 2017-08-30 20:14 UTC
This might be a stupid question, but I have no idea what needs to be done in order to use the editor.

I have an ESP8266 with ESP3D v0.6.2 installed and configured. How would I go about to add / enable the editor and access it from the ESP3D menu?

**Comment by apphead** [comment] 2017-08-30 23:06
After digging a little deeper, I found ESP3D-WEBUI which includes the editor and seems more up-to-date than ESP3D's interface. But again, installation failed. This is how far I got:
- downloaded ESP3D/devt firmware 
- replaced the index.html.gz in /data/ of ESP3D
- In Arduino, I installed board https://github.com/esp8266/Arduino/releases/tag/2.4.0-rc1
- compilation and upload of ESP3D and the SPIFF upload all successful
Now, I can connect to the board via TCP/IP, but all it tells me is:
![2017-08-31 01_02_56-esp3d webui](https://user-images.githubusercontent.com/505490/29898828-3a771a52-8de8-11e7-8440-da2127a70383.png)
What firmware? Repetier or ESP3D? For testing purposes, I use the ESP8266 as a single module without DUE / RADDS wired up. Is that a problem. With ESP3D v0.6.2, it connected without DUE / RADDS....

**Comment by luc-github** [comment] 2017-08-31 07:10
Hi,
About first question : you need to copy config.html.gz on SPIFFS and call config.html from browser
about ESP3D-WEBUI, yes it is more up to date UI and it need the devt branch of ESP as linked in installation step https://github.com/luc-github/ESP3D-WEBUI#installation:
 https://github.com/luc-github/ESP3D/tree/devt

the message you got means you may using the master instead of devt - as I rewrited the ESP3D firmware for this UI. 
The ESP3D devt branch will be merged once ESP3D-WEBUI will be ready - as currently I am ending coding first setup page wizards  and will add the missing authentication pages present in master branch.

Once the ESPWEB-UI will support authentication it will become the UI of master, but until this is done (I hope soon), it will use devt branch of ESP3D as linked in installation.

I hope it help not beeing a shame

**Comment by luc-github** [comment] 2017-08-31 13:16
Yes Printing from SD is the safer way IMHO
The editor tab appear when repetier or smoothieware is set as target FW in ESP-WEBUI
the setup should help to clarify that - I just finished it today - just  spanish / german translation are not done yet
![image](https://user-images.githubusercontent.com/8822552/29924980-26a51b24-8e5f-11e7-8013-af2d8a8e4b3d.png)
Will release it when authentication is back hope this week is done

**Comment by apphead** [comment] 2017-08-31 14:48
Editor tab shows as soon as target FW is set correctly.

I get an error when trying to load the values. Failed:406 Wrong data
Are there any flags that must be set in Repetier firmware, like JSON_out? (I use latest dev)

Can't wait to pull the latest release and start testing the reliability of SD printing!!

**Comment by luc-github** [comment] 2017-08-31 14:58
be sure baud rate are identical on printer and ESP
the config tab is just catching the M205 command 's response - it does not rely on JSON for this one, so repetier default flags should works but I did not check on latest repetier but should be OK

**Comment by luc-github** [comment] 2017-08-31 15:01
Current version is already supporting SD printing - what it is not available is a scan of an SD card directly connected to ESP, but SD card used by repetier FW is working

**Comment by apphead** [comment] 2017-09-02 06:06
Hmm, I double checked baud rate (250000), sdcard settings on Repetier FW and ESP3D, SD card is FAT32, connected to Arduino DUE, but I cannot upload or list any files or create a folder... Any ideas?

By the way: According to http://forums.reprap.org/read.php?336,719437 the baudrate in Repetier Firmware is 
#define BLUETOOTH_SERIAL 1
#define BLUETOOTH_BAUD 250000

Or is it BAUDRATE that needs to be identical?

**Comment by luc-github** [comment] 2017-09-02 07:23
settings seems OK 
Nothing is working ?
can you give me a screen shoot of UI ? and errors ?

this is old  editor repository and you are talking about file upload - so I want to be sure of what interface you are using and what problem you have

**Comment by luc-github** [comment] 2017-09-06 07:41
I just commit several update and fixes on https://github.com/luc-github/ESP3D/tree/devt and  https://github.com/luc-github/ESP3D-WEBUI
I cannot reproduce this issue unless rx/tx are updside down (bad connection)
Please check and open issue in proper github as now this one is discontinued

Thank you

**Closed by luc-github** 2017-09-06 07:41 UTC
Labels: question
